export const regions = [
  {
    name: 'europe',
    cities: [
      'Andorra la Vella',
      'Vienna',
      'Yerevan',
      'Brussels',
      'Copenhagen',
      'Helsinki',
      'Paris',
      'Berlin',
      'Athens',
      'Dublin',
      'Rome',
      'Luxembourg',
      'Amsterdam',
      'Oslo',
      'Warsaw',
      'Lisbon',
      'Bucharest',
      'Moscow',
      'San Marino',
      'Madrid',
      'Stockholm',
      'Bern',
      'Ankara',
      'Kiev',
      'London',
    ],
  },
  {
    name: 'america',
    cities: [
      'Buenos Aidres',
      'La Paz',
      'Brasilia',
      'Ottawa',
      'Santiago',
      'Bogotá',
      'San José',
      'La Habana',
      'Santo Domingo',
      'Quito',
      'San Salvador',
      'Washington D.C.',
      'Ciudad de Guatemala',
      'Georgetown',
      'Puerto Príncipe',
      'Tegucigalpa',
      'Kingston',
      'Ciudad de México',
      'Managua',
      'Ciudad de Panamá',
      'Asunción',
      'Lima',
      'San Juan',
      'Kingstown',
      'Montevideo',
      'Caracas',
    ],
  },
  {
    name: 'argentina',
    cities: [
      'Buenos Aires',
      'La Plata',
      'Córdoba',
      'Rosario',
      'Mendoza',
      'Tucumán',
      'Salta',
      'San Juan',
      'San Luis',
      'Catamarca',
      'Santiago del Estero',
      'Jujuy',
      'Chaco',
      'Formosa',
      'Misiones',
      'Corrientes',
      'Entre Ríos',
      'Santa Fe',
      'Chubut',
      'Neuquén',
      'Río Negro',
      'Santa Cruz',
      'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
    ],
  },
];
